# 1st assignment 

### torch.tensor

An short introduction about PyTorch and about the few functions. 
#### > torch.cat
#### > torch.reshape
#### > torch.take
#### > torch.view
#### > torch.matmul

In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.cat

Concatenates the given sequence of tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [10]:
# Example 1 - working 
x = torch.randn(3, 3)
print(torch.cat((x, x, x), 0))


tensor([[ 0.1039, -2.6805, -0.4652],
        [-1.3789,  0.9217, -1.0212],
        [ 1.1273, -0.6954,  0.4879],
        [ 0.1039, -2.6805, -0.4652],
        [-1.3789,  0.9217, -1.0212],
        [ 1.1273, -0.6954,  0.4879],
        [ 0.1039, -2.6805, -0.4652],
        [-1.3789,  0.9217, -1.0212],
        [ 1.1273, -0.6954,  0.4879]])
tensor([[ 0.1039, -2.6805, -0.4652,  0.1039, -2.6805, -0.4652,  0.1039, -2.6805,
         -0.4652],
        [-1.3789,  0.9217, -1.0212, -1.3789,  0.9217, -1.0212, -1.3789,  0.9217,
         -1.0212],
        [ 1.1273, -0.6954,  0.4879,  1.1273, -0.6954,  0.4879,  1.1273, -0.6954,
          0.4879]])


Concatenates tensor  3 times and create new tensor

In [11]:
# Example 2 - working
torch.cat((x, x, x), 1)

tensor([[ 0.1039, -2.6805, -0.4652,  0.1039, -2.6805, -0.4652,  0.1039, -2.6805,
         -0.4652],
        [-1.3789,  0.9217, -1.0212, -1.3789,  0.9217, -1.0212, -1.3789,  0.9217,
         -1.0212],
        [ 1.1273, -0.6954,  0.4879,  1.1273, -0.6954,  0.4879,  1.1273, -0.6954,
          0.4879]])

Concatenates tensor 3 times in another axis

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
y = torch.randn(3,2)
torch.cat((x, y), 0)

RuntimeError: ignored

he size of x tensor is 3 by 3 and y is 3 by 2 which is a mismatch and must have to match to concatenate

The function is used to concatenate

## Function 2 - torch.reshape

It takes input and reshape size and returns a tensor with the same data and number of elements as input

In [27]:
# Example 1 - working
x = torch.randn(10)
print(x)
torch.reshape(x, (5, 2))

tensor([-0.7901,  0.3933, -0.0400,  0.0689, -2.0546,  1.6476,  0.6646, -1.1649,
        -0.4212, -2.1569])


tensor([[-0.7901,  0.3933],
        [-0.0400,  0.0689],
        [-2.0546,  1.6476],
        [ 0.6646, -1.1649],
        [-0.4212, -2.1569]])

Reshape a 1D array to 5 by 2 dimension

In [22]:
# Example 2 - working
y = torch.tensor([[-0.6784,  0.8212],
        [-0.0244, -0.3806],
        [-0.9986, -1.6126],
        [-0.1749,  1.3988],
        [-0.9295,  0.5233]])
torch.reshape(y, (-1,))

tensor([-0.6784,  0.8212, -0.0244, -0.3806, -0.9986, -1.6126, -0.1749,  1.3988,
        -0.9295,  0.5233])

Reshape a tensor of size 5 by 2 to size of shape 1

In [25]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.arange(11)
torch.reshape(x, (2, 3))

RuntimeError: ignored

The function could not change the shape to size 2 by 3 because of size 11

Change the shape of input

## Function 3 - torch.take

Takes a tensor and returns a new tensor with the elements of inputs at the given indices

In [40]:
# Example 1 - working
x = torch.randn(5,2,3)
print(x)
torch.take(x, torch.tensor([0, 6, 10]))


tensor([[[ 1.4548, -0.3098, -0.6392],
         [-1.2620, -0.1484, -0.5098]],

        [[ 0.0906,  1.4270, -0.1366],
         [ 1.1127, -0.0789, -1.0563]],

        [[ 0.2826,  0.4658, -0.5280],
         [ 0.7558, -0.7301,  0.4031]],

        [[-0.2038, -0.5511, -0.1244],
         [ 0.0514,  1.0462,  0.2506]],

        [[ 0.7080, -0.7573, -0.7082],
         [-0.4799, -1.3008, -0.3812]]])


tensor([ 1.4548,  0.0906, -0.0789])

Takes a tensor of shape 5, 2, 3 and returns a new tensor with the indices value 0, 6, 10

In [43]:
# Example 2 - working
y = torch.tensor([[5, 3, 5],
                 [1, 5, 5]])
print(y)
torch.take(y, torch.tensor([3, 3]))

tensor([[5, 3, 5],
        [1, 5, 5]])


tensor([1, 1])

Returns a new tensor with indices value of 3 and 3

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(1,4,3)
print(x)
torch.take(x, torch.tensor([0, 2, 13]))

tensor([[[ 0.0234, -0.2771, -1.3984],
         [ 1.0113, -0.7154,  0.3183],
         [-0.2716, -1.2234,  0.6337],
         [ 0.9134, -0.0639, -0.5973]]])


RuntimeError: ignored

x tensor have indices upto 12. There is not tensor to 13



This function is useful to get the required values from other tensor

## Function 4 - torch.view

It takes input and reshape size and returns a tensor with the same data and number of elements as input.But, Input won't change it shape when we call it in next instruction.


In [56]:
# Example 1 - working
t = torch.rand(4, 4)
print(t.view(2, 8))
print(t)

tensor([[0.2272, 0.4060, 0.0343, 0.7325, 0.5882, 0.7602, 0.1602, 0.9939],
        [0.9084, 0.2754, 0.8336, 0.5572, 0.7834, 0.1227, 0.2128, 0.1336]])
tensor([[0.2272, 0.4060, 0.0343, 0.7325],
        [0.5882, 0.7602, 0.1602, 0.9939],
        [0.9084, 0.2754, 0.8336, 0.5572],
        [0.7834, 0.1227, 0.2128, 0.1336]])


Explanation about example

In [63]:
# Example 2 - working
t = torch.rand(4, 4)
print(t.view(16,-1))
print(t.view(-1,16))
print(t.view(-1))

tensor([[0.2258],
        [0.8424],
        [0.5797],
        [0.8566],
        [0.0726],
        [0.2611],
        [0.4458],
        [0.4279],
        [0.9115],
        [0.5694],
        [0.7163],
        [0.8941],
        [0.7591],
        [0.6354],
        [0.5651],
        [0.4007]])
tensor([[0.2258, 0.8424, 0.5797, 0.8566, 0.0726, 0.2611, 0.4458, 0.4279, 0.9115,
         0.5694, 0.7163, 0.8941, 0.7591, 0.6354, 0.5651, 0.4007]])
tensor([0.2258, 0.8424, 0.5797, 0.8566, 0.0726, 0.2611, 0.4458, 0.4279, 0.9115,
        0.5694, 0.7163, 0.8941, 0.7591, 0.6354, 0.5651, 0.4007])


shaping in 1D in x-axis and y-axis

In [64]:
# Example 3 - breaking (to illustrate when it breaks)
t = torch.rand(4, 4)
print(t.view(10,-1))

RuntimeError: ignored

Input size is 16. 10 is invalid 

changing the shape of input

## Function 5 - torch.matmul

Returns product of tensors

In [66]:
# Example 1 - working
x = torch.randn(3, 3)
y = torch.randn(3, 1)
torch.matmul(x, y)

tensor([[-1.2175],
        [ 0.0543],
        [ 0.2915]])

Multiply x and y

In [70]:
# Example 2 - working
x = torch.randn(3, 3, 5, 5)
y = torch.inverse(x)
torch.matmul(x, y)

tensor([[[[ 1.0000e+00, -8.9407e-08,  5.9605e-08,  2.9802e-08,  6.7055e-08],
          [ 0.0000e+00,  1.0000e+00,  0.0000e+00, -5.9605e-08, -5.9605e-08],
          [ 2.2352e-08,  5.9605e-08,  1.0000e+00, -7.6368e-08, -7.4506e-09],
          [ 6.7987e-08,  0.0000e+00,  2.2352e-08,  1.0000e+00, -2.7940e-08],
          [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.1921e-07,  1.0000e+00]],

         [[ 1.0000e+00,  1.1921e-07, -2.0862e-07, -2.3842e-07, -2.0862e-07],
          [ 0.0000e+00,  1.0000e+00,  3.5763e-07,  2.3842e-07,  2.3842e-07],
          [ 1.1921e-07, -1.1921e-07,  1.0000e+00,  1.1921e-07,  5.9605e-08],
          [-5.9605e-08, -1.7881e-07,  5.9605e-08,  1.0000e+00,  1.7881e-07],
          [ 1.9372e-07, -8.9407e-08,  7.4506e-08,  1.7881e-07,  1.0000e+00]],

         [[ 1.0000e+00,  2.6077e-08,  8.8476e-09,  1.8626e-08, -1.3039e-08],
          [-2.9802e-08,  1.0000e+00, -2.9802e-08, -1.1921e-07,  0.0000e+00],
          [-2.9802e-08, -5.9605e-08,  1.0000e+00, -1.4901e-07,  0.0000e+

Multiply matrix "x" and it's inverse "y"

In [71]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(3, 2)
y = torch.randn(3, 1)
torch.matmul(x, y)

RuntimeError: ignored

Cannot multiply 3 by 2 matrix with 3 by 1

tensor multiplication

## Conclusion

This notebook contains of 5 functions from pytorch documentation.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* ...

In [72]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 2.0MB/s 


In [0]:
import jovian

In [76]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
